server:
  port: 9001
  address: 127.0.0.1

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
#    sentinel:
#      transport:
#        dashboard: 172.18.241.71:8080 #sentinel dashboard的地址
#        #默认8719，如果被占用会自动从8719开始一次+1扫描，直至找到未被占用的端口。
#        port: 8719
  redis:
    database: 0
    host: 192.168.50.110
    port: 6379
    password:
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0




  # redis集群配置
#  redis:
#    lettuce:
#      pool:
#        # 连接池最大连接数（使用负值表示没有限制）
#        max-active: 20
#          # 连接池最大阻塞等待时间（使用负值表示没有限制）
#        max-wait: -1
#          # 连接池中的最大空闲连接
#        max-idle: 20
#          # 连接池中的最小空闲连接
#        min-idle: 0
#        # 连接超时时间（毫秒）
#        time-between-eviction-runs: 60000
#    cluster:
#      nodes:
#        - 192.168.50.110:6379
#        - 192.168.50.110:6380
#        - 192.168.50.110:6381
#        - 192.168.50.110:6382
#        - 192.168.50.110:6383
#        - 192.168.50.110:6384
#    # Redis服务器连接密码（默认为空）
#    password:
#    timeout: 6000

management:
  endpoints:
    web:
      exposure:
        include: "*"











logging:
  level:
    com.a: debug
    root: info
  file: ./logs/core.log
