server:
  port: 83

spring:
  application:
    name: nacos-order-consumer
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8080 #sentinel dashboard的地址
        #默认8719，如果被占用会自动从8719开始一次+1扫描，直至找到未被占用的端口。
        port: 8719

#消费者将要去访问的微服务名称（注册成功进nacos的微服务提供者）
service-url:
  nacos-user-service: http://nacos-payment-provider
# 设置feign客户端超时时间(OpenFeign默认支持ribbon)
ribbon:
  # 指的是建立连接所用的时间
  # 指的是建立连接后从服务器读取到可用资源所用的时间
  ReadTimeout: 5000
  ConnectTimeout: 5000
#
logging:
  level:
    # feign日志以什么级别监控哪个接口
    com.a.service.FeignClient: debug