server:
  port: 8001

spring:
  application:
    name: cloud-payment-service #服务名称
  zipkin:
    base-url: http://localhost:9411
    sleuth:
      sampler:
        probability: 1

eureka:
  client:
    register-with-eureka: true #表示向注册中心注册自己 默认为true
    fetch-registry: true #是否从EurekaServer抓取已有的注册信息，默认为true,单节点无所谓,集群必须设置为true才能配合ribbon使用负载均衡
    service-url:
      defaultZone: http://eureka7001:7001/eureka/ #不集群
#        defaultZone: http://eureka7001:7001/eureka/, http://eureka7002:7002/eureka/ # 入驻地址 集
  instance:
    instance-id:  hystrix8001