server:
  port: 80
  servlet:
    session:
      cookie:
        name: OAUTH2-CLIENT-SESSIONID #防止Cookie冲突，冲突会导致登录验证不通过
oauth2-server-url: http://localhost:9401
spring:
  application:
    name: cloud-order-service
  zipkin:
    base-url: http://localhost:9411
    sleuth:
      sampler:
        probability: 1

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7001:7001/eureka/, http://eureka7002:7002/eureka/ # 入驻地址集群
feign:
  hystrix:
    enabled: true #在feign中开启hystrix

# 安全认证的配置
security:
  oauth2: #与oauth2-server对应的配置
    client:
      client-id: admin
      client-secret: admin123456
      user-authorization-uri: ${oauth2-server-url}/oauth/authorize
      access-token-uri: ${oauth2-server-url}/oauth/token
    resource:
      jwt:
        key-uri: ${oauth2-server-url}/oauth/token_key
#  basic:
#    enabled: true
